### PR TITLE
Allow setting thermostat temperature when mode is off

### PR DESCRIPTION
**Pull request by amosyuen**
Allow setting thermostat temperature when mode is off

### CODE REVIEW

**Comment by amosyuen** [comment]
Resolves #50

**Comment by mbudnek** [comment]
I really appreciate the contribution, and I'm sorry I let this PR languish for so long.  I like the idea behind this change, but I think it needs to do a bit more to be really useful.  Always blindly setting the heating setpoint when the thermostat is off doesn't really make a lot of sense to me.  Maybe if it checked if the new setpoint was above or below the current one and set the heating or cooling setpoint as appropriate?

**Comment by amosyuen** [comment]
That's a good point. But if I think about it more, I would say determining setpoint as based on mode or based on the current setpoint is actually not right.

From my understanding when setting the temperature using google, you're really setting the desired temperature. The setpoint that should be changed should probably be based on the current temp and supported modes. For example:
* If it is currently 80 and I want to set it to 70, then the cooling setpoint should be set to 70 so that A/C kicks in.
* If it is 50 and I want the temperature to be 60, the heating setpoint should be set to 60 so heating kicks in.

Of course, if you don't support both heating and cooling you should just set the setpoint that is supported.

So the setpoint shouldn't be determined by the current mode. In the example above, even if it's currently heating to 90 from 80, and I say set temperature to 70. I would want the cooling setpoint to be changed so that AC kicks. With the current way it is, just the heating setpoint would be changed, which would just stop the heating but wouldn't start cooling.

**Comment by mbudnek** [comment]
I mostly agree with your assessment, with the additional thought that, IMO, that should only be the behavior when the thermostat is off.  If it's on then it should always set the setpoint for the currently active mode.  If I'm cold in the summer I generally don't want to switch my thermostat to heating mode; I just want to turn the cooling setpoint up so that it shuts off for a bit.

**Comment by amosyuen** [comment]
I tested out how native google integration with ecobee works, and looks like it is somewhat mode dependent. So I think as you said probably makes sense to only do it for `off` mode and for `heatcool` mode.

**Pull request closed without merging**
